"""gen_and_test_configs.py — build several realistic compiler configs and run the
test harness on each, for both cultivation circuits.

Config shapes:
  mono    : 1 leaf (all qubits) + root                       (2 layers)
  strip2  : 2 leaves split by x                               (2 layers)
  strip4  : 4 leaves split by x                               (2 layers)
  grid4   : 4 leaves split by (x,y) into a 2x2 grid           (2 layers)
  tree3   : 4 x-strip leaves -> 2 routers -> root             (3 layers)
"""

from __future__ import annotations

import json
import os
import re
from collections import defaultdict


def _collapse_int_arrays(text: str) -> str:
    """Put arrays of integers (qubit lists, children) on one line, keeping the
    rest of the indented structure."""
    return re.sub(r"\[[\d,\s]+\]",
                  lambda m: re.sub(r"\s+", " ", m.group(0)).replace("[ ", "[").replace(" ]", "]"),
                  text)

import stim

from parser import DetectorConstructionScanner
from config import CompilerConfig
from compiler import Compiler
from test_harness import run_test

DATA = "data"
CIRCUITS = {
    "d3d9": "../../../magic_state_cultivation/circuits_dump/"
            "c=end2end-inplace-distillation,p=0.001,noise=uniform,g=css,q=166,b=Y,r=11,r1=3,d1=3,r2=3,d2=9.stim",
    "d5d11": "../../../magic_state_cultivation/circuits_dump/"
             "c=end2end-inplace-distillation,p=0.001,noise=uniform,g=css,q=255,b=Y,r=16,r1=3,d1=5,r2=3,d2=11.stim",
}
# Postselect sets come from the decoder workflow's circuit-folder JSONs
# (generated by algorithms/get_desaturated_dem_with_obs_detector.py); the
# generated configs inline the list so they stay self-contained.
POSTSELECT_JSON = {
    "d3d9": "data/cultivation_d1_3_d2_9/postselected_detectors.json",
    "d5d11": "data/cultivation_d1_5_d2_11/postselected_detectors.json",
}


def _load_postselect(cname):
    path = POSTSELECT_JSON[cname]
    if not os.path.isfile(path):
        raise SystemExit(
            f"missing {path} — generate it with "
            f"algorithms/get_desaturated_dem_with_obs_detector.py for {cname}.")
    with open(path) as f:
        return sorted(json.load(f)["postselected_detectors"])


# --------------------------------------------------------------------------- #
def _qubits(coords):
    return [q for q, xy in enumerate(coords) if xy is not None]


def _strips(vals, n):
    """n index-balanced cut points over the sorted distinct values."""
    u = sorted(set(vals))
    bounds = [u[int(round(i * len(u) / n))] for i in range(n)] + [u[-1] + 1]
    return bounds


def partition_x(coords, nx):
    qs = _qubits(coords)
    b = _strips([coords[q][0] for q in qs], nx)
    buckets = defaultdict(list)
    for q in qs:
        x = coords[q][0]
        buckets[max(i for i in range(nx) if b[i] <= x)].append(q)
    return [sorted(buckets[i]) for i in range(nx) if buckets[i]]


def partition_grid(coords, nx, ny):
    qs = _qubits(coords)
    bx = _strips([coords[q][0] for q in qs], nx)
    by = _strips([coords[q][1] for q in qs], ny)
    buckets = defaultdict(list)
    for q in qs:
        x, y = coords[q]
        ix = max(i for i in range(nx) if bx[i] <= x)
        iy = max(i for i in range(ny) if by[i] <= y)
        buckets[(ix, iy)].append(q)
    return [sorted(v) for v in buckets.values() if v]


# --------------------------------------------------------------------------- #
def make_config(name, leaf_qubits, router_groups=None, kern=None, postselect=()):
    kern = kern or {"count": 256, "n": 16, "h": 8}    # generous compact kernels (pass 1)
    leaves = [{"board_id": i, "qubits": ql, "kernels": dict(kern), "raw_out": 99999}
              for i, ql in enumerate(leaf_qubits)]
    layers = [{"level": 0, "type": "leaf", "boards": leaves}]
    if router_groups is None:
        layers.append({"level": 1, "type": "root", "boards": [
            {"board_id": 9999, "children": [b["board_id"] for b in leaves], "kernels": dict(kern)}]})
    else:
        routers = [{"board_id": 1000 + ri, "children": [leaves[i]["board_id"] for i in grp],
                    "kernels": dict(kern), "raw_out": 99999}
                   for ri, grp in enumerate(router_groups)]
        layers.append({"level": 1, "type": "router", "boards": routers})
        layers.append({"level": 2, "type": "root", "boards": [
            {"board_id": 9999, "children": [r["board_id"] for r in routers], "kernels": dict(kern)}]})
    return {"name": name, "version": 1, "hardware": {"layers": layers},
            "postselect": sorted(postselect)}


def tighten(cfg_dict, comp):
    """Size each board's kernels to its actual need (channel count / n / h) with a
    little headroom, using the compact uniform-kernel form for readability."""
    for layer in cfg_dict["hardware"]["layers"]:
        for b in layer["boards"]:
            ch = comp.programs[b["board_id"]].channels
            b["kernels"] = {
                "count": max(1, len(ch) + 1),
                "n": max((len(c.support) for c in ch), default=1) + 1,
                "h": max((c.required_h for c in ch), default=1) + 1,
            }
    cfg_dict["name"] += "_sized"


def configs_for(coords, postselect):
    return {
        "mono":   make_config("mono",   [_qubits(coords)], postselect=postselect),
        "strip2": make_config("strip2", partition_x(coords, 2), postselect=postselect),
        "strip4": make_config("strip4", partition_x(coords, 4), postselect=postselect),
        "grid4":  make_config("grid4",  partition_grid(coords, 2, 2), postselect=postselect),
        "tree3":  make_config("tree3",  partition_x(coords, 4), router_groups=[[0, 1], [2, 3]],
                              postselect=postselect),
    }


# --------------------------------------------------------------------------- #
if __name__ == "__main__":
    os.makedirs(DATA, exist_ok=True)
    results = []
    for cname, path in CIRCUITS.items():
        circuit = stim.Circuit.from_file(path)
        s = DetectorConstructionScanner.from_file(path)
        s.scan(); s.refine()
        coords = s._physical_qubits_coord_raw
        postselect = _load_postselect(cname)
        for shape, gen_dict in configs_for(coords, postselect).items():
            comp1 = Compiler(CompilerConfig(gen_dict), s)          # pass 1: generous
            tighten(gen_dict, comp1)                               # size kernels to need
            fn = f"{DATA}/config_{cname}_{shape}.json"
            with open(fn, "w") as f:
                f.write(_collapse_int_arrays(json.dumps(gen_dict, indent=2)))  # readable, sized
            cfg = CompilerConfig.from_file(fn)                     # pass 2: sized config
            comp = Compiler(cfg, s)
            feasible = all(not comp.programs[b].problems for b in cfg.boards)
            nboards = len(cfg.boards)
            depth = len(gen_dict["hardware"]["layers"])
            print("=" * 70)
            print(f"{cname} / {shape}: {nboards} boards, {depth} layers, feasible={feasible}")
            ok = run_test(circuit=circuit, comp=comp, shots=1000) if feasible else False
            results.append((cname, shape, nboards, depth, feasible, ok))

    print("\n" + "=" * 70 + "\nSUMMARY")
    print(f"{'circuit':7} {'shape':7} {'boards':6} {'layers':6} {'feasible':8} {'test'}")
    for c, sh, nb, dp, fe, ok in results:
        print(f"{c:7} {sh:7} {nb:<6} {dp:<6} {str(fe):8} {'PASS' if ok else 'FAIL'}")
